In [ ]:
#https://www.cvxpy.org/
#https://www.cvxpy.org/tutorial/advanced/index.html
#https://www.pythontutorial.net/python-basics/python-read-text-file/
import numpy as np
import cvxpy as cp
from scipy.io import wavfile
import librosa    
from pathlib import Path
from google.colab import drive

In [ ]:
# # ##UNCOMMENT EACH TIME

drive.mount('/content/gdrive')

!unzip gdrive/MyDrive/p2.zip
!unzip gdrive/MyDrive/p3.zip
!unzip gdrive/MyDrive/p4.zip
!unzip gdrive/MyDrive/p6.zip
!unzip gdrive/MyDrive/p5.zip

!unzip gdrive/MyDrive/g2.zip
!unzip gdrive/MyDrive/g3.zip
!unzip gdrive/MyDrive/g4.zip
!unzip gdrive/MyDrive/g6.zip
!unzip gdrive/MyDrive/g5.zip

Streaming output truncated to the last 5000 lines.
  inflating: g4/0537.wav             
  inflating: __MACOSX/g4/._0537.wav  
  inflating: g4/0906.wav             
  inflating: __MACOSX/g4/._0906.wav  
  inflating: g4/0912.wav             
  inflating: __MACOSX/g4/._0912.wav  
  inflating: g4/0084.wav             
  inflating: __MACOSX/g4/._0084.wav  
  inflating: g4/0090.wav             
  inflating: __MACOSX/g4/._0090.wav  
  inflating: g4/0709.wav             
  inflating: __MACOSX/g4/._0709.wav  
  inflating: g4/0047.wav             
  inflating: __MACOSX/g4/._0047.wav  
  inflating: g4/0721.wav             
  inflating: __MACOSX/g4/._0721.wav  
  inflating: g4/0735.wav             
  inflating: __MACOSX/g4/._0735.wav  
  inflating: g4/0053.wav             
  inflating: __MACOSX/g4/._0053.wav  
  inflating: g4/0872.wav             
  inflating: __MACOSX/g4/._0872.wav  
  inflating: g4/0866.wav             
  inflating: __MACOSX/g4/._0866.wav  
  inflating: g4/0696.wav             

In [ ]:
with open('train.txt') as train_file:
    count = 0
    spectrogram_piano = np.zeros((9000, 4000)) #4000 samples
    spectrogram_guitar = np.zeros((9000, 4000)) #b
    for entry in train_file:
        split_entry = entry.split(",")
        folder = split_entry[0].strip()
        t_wav = split_entry[1].strip()

        input_name = '/content/p'+ folder+ '/' + t_wav +'.wav'
        output_name = '/content/g'+ folder+ '/' + t_wav +'.wav'

        spectrogram_piano[:,count] = librosa.load(input_name, sr=3000)[0].flatten() #x
        spectrogram_guitar[:,count] = librosa.load(output_name, sr=3000)[0].flatten() #b
        count += 1

spect piano (9000x19) for 19 samples 
spect guitar (9000x19) for same 19 samples 


In [ ]:
print(spectrogram_piano)

[[ 4.65467601e-04 -4.86890291e-04  7.09942076e-04 ...  7.73136097e-04
   4.11212066e-04  7.49161118e-04]
 [ 5.23301678e-05  3.16188368e-03  1.97266927e-03 ... -1.74528908e-03
   5.05113928e-03  4.26094019e-04]
 [-4.76635713e-03  8.33903719e-03 -7.15211220e-03 ... -2.21431116e-03
   1.00617828e-02 -8.55535362e-03]
 ...
 [ 4.44590005e-05  6.19325746e-08  2.71509307e-05 ...  1.86187190e-05
  -3.03977868e-06 -3.42047097e-05]
 [ 3.45903609e-05  8.14569194e-06  3.71826463e-05 ...  4.15052637e-06
   5.90015725e-06 -8.44987426e-06]
 [-5.82285747e-06  3.48592330e-05  3.37274105e-05 ... -1.31540110e-05
   1.84092823e-06  2.20276684e-06]]


In [ ]:
x_inv = np.linalg.pinv(spectrogram_piano)

A = spectrogram_guitar@x_inv # A = b * psuedo inverse of x

[[ 5.90160187e+02 -3.07462675e+03  7.55913416e+02 ...  1.21131708e+01
   3.88966743e+00 -3.01439549e+00]
 [ 3.84435952e+02  1.97993850e+03  1.88896142e+03 ... -4.97657130e-01
   8.74773981e+00  2.88112607e-01]
 [ 1.20568055e+02 -3.72747224e+03  1.21143954e+03 ...  3.95919462e+00
  -1.56663696e+01 -1.75198733e+01]
 ...
 [ 2.15866980e+02  2.97925029e+03  8.52451810e+03 ...  2.89349955e+01
  -9.61836351e+00 -6.60945824e+00]
 [ 6.06010912e+02  5.45410038e+03 -2.59132432e+03 ...  4.06384642e+00
  -1.06530120e+01 -9.64318686e+00]
 [ 1.78236922e+03 -4.86070678e+03 -3.59733442e+03 ... -1.40492395e+01
   1.23260893e+01 -9.86245907e+00]]


In [ ]:
# Testing the diff
diff = A@spectrogram_piano - spectrogram_guitar
print(diff)

[[ 2.80888648e-13 -2.93374740e-13 -6.92436397e-13 ... -3.24177629e-13
  -8.91654855e-16 -3.94237811e-13]
 [-1.04239382e-12 -8.86740022e-13 -1.41930087e-13 ...  1.53605655e-12
  -1.54624786e-12 -7.34771619e-13]
 [-2.90586579e-12 -4.69592681e-12 -4.29138626e-12 ... -1.59127269e-13
  -1.81559433e-12  1.67452944e-12]
 ...
 [ 5.45091451e-15 -4.03251380e-14 -2.63450631e-13 ... -1.71807650e-13
  -4.61390671e-14  1.20112186e-14]
 [ 1.00468623e-13 -8.44567743e-15 -9.56133298e-14 ... -6.24144071e-14
   3.52893848e-14  6.89522597e-14]
 [ 4.63092462e-14 -1.21428502e-13 -1.53094276e-13 ... -6.17298943e-14
   6.32786941e-14  1.02896983e-13]]


In [ ]:
spectrogram_piano_test = np.zeros((9000, 1)) #X
spectrogram_piano_test[:,0] = librosa.load('/content/p3/0001.wav', sr=3000)[0].flatten()

spectrogram_guitar_test = np.zeros((9000, 1)) #B
spectrogram_guitar_test[:,0] = librosa.load('/content/g3/0001.wav', sr=3000)[0].flatten()

# reconstructed guitar sound -> AX
guitar_reconst = A@spectrogram_piano_test
print(guitar_reconst)

print(spectrogram_guitar_test)

# Write to output files
from __future__ import print_function
import scipy.io.wavfile as wavf
import numpy as np

wavf.write('specto_piano_test0001.wav', 3000, spectrogram_piano_test)
wavf.write('reconst_guitar_0001.wav', 3000, guitar_reconst)
wavf.write('specto_guitar_test0001.wav', 3000, spectrogram_guitar_test)

[[-1.90267716e-04]
 [-8.94137962e-04]
 [-1.63599851e-03]
 ...
 [ 2.55650635e-05]
 [ 1.50298459e-05]
 [ 1.84940106e-05]]
[[-1.90352381e-04]
 [-8.93977995e-04]
 [-1.63626135e-03]
 ...
 [ 2.55650793e-05]
 [ 1.50298356e-05]
 [ 1.84940527e-05]]


MORE TESTING


In [ ]:
spectrogram_piano_test = np.zeros((9000, 1)) #x
spectrogram_piano_test[:,0] = librosa.load('/content/p4/0004.wav', sr=3000)[0].flatten()

guitar_reconst = A@spectrogram_piano_test
print(guitar_reconst)

from __future__ import print_function
import scipy.io.wavfile as wavf
import numpy as np

wavf.write('specto_piano_test40004.wav', 3000, spectrogram_piano_test)
wavf.write('reconst_guitar_40004.wav', 3000, guitar_reconst)
# wavf.write('specto_guitar_test40004.wav', 3000, spectrogram_guitar_test)

[[-4.74314468e-05]
 [-9.48409957e-04]
 [-3.63957963e-04]
 ...
 [-3.85979335e-05]
 [-3.98829428e-05]
 [-4.43747292e-05]]


In [ ]:
spectrogram_guitar_test = np.zeros((9000, 1)) #b
spectrogram_guitar_test[:,0] = librosa.load('/content/g4/0004.wav', sr=3000)[0].flatten()
wavf.write('specto_guitar_test40004.wav', 3000, spectrogram_guitar_test)
print(spectrogram_guitar_test)

[[-4.74284388e-05]
 [-9.48418688e-04]
 [-3.63944360e-04]
 ...
 [-3.85979693e-05]
 [-3.98829397e-05]
 [-4.43747194e-05]]
